### ISSUE TITLE
Attachment Interface

### ISSUE THREAD

**Issue by Funfare** [laravel-notification-channels/rocket-chat#11]
Hi @antonkomarev ,

want to know your oppinion. I would switch for the Attachment to a Contract/RocketChatAttachment in public interface, so that a user may can add his own Attachment, for example a Eloquent Model or whatever.

So Interface would require a method like `public function toRocketChatAttachmentArray():array` and our class would be just the "default" use case.

Do you agree with that idea?  Then i would implement that.

**Comment by antonkomarev** [comment]
I don't think that's good solution. Because in this case this model will require to know how rocket chat array should look like.

If you need to have an easy way to pass your application model to Rocket.Chat - you may add special RocketChatAttachment builder method in it.

```php
namespace App;

class Image extends Model
{
    // Other model methods

    public function toRocketChatAttachment(): RocketChatAttachment
    {
        // Put building logic here
    }
}
```

Or have separate service class which will be responsible for this transformation.
